# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run selenide tests

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
jobs:
  run-tests-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run tests in Gradle
      run: ./gradlew clean test -Dselenide.headless=true --info --rerun-tasks
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: gradle test report
        path:  build/reports